name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile sources
        run: |
          mkdir -p build
          javac -d build $(find src -name "*.java")

      - name: Run main class
        run: java -cp build numberwordcountdownproject.NumberWordCountdownProject
